import { ScrapedJob } from "./scraper-logic";

export const MOCK_JOBS: ScrapedJob[] = [
  {
    title: "Senior Frontend Engineer",
    company: "Vercel",
    location: "Remote, India",
    salary: "₹45L - ₹65L",
    jobType: "Full-time",
    description: "Join the Next.js team and help build the future of the web. Experience with React, TypeScript, and performance optimization is essential.",
    jobUrl: "https://example.com/job/1",
    benefits: ["Health Insurance", "Remote Work", "Equity"],
    qualifications: ["5+ years React experience", "Strong TS skills"]
  },
  {
    title: "UI/UX Designer",
    company: "Airbnb",
    location: "Bangalore, KA",
    salary: "₹30L - ₹45L",
    jobType: "Full-time",
    description: "Design beautiful and intuitive experiences for travelers worldwide. Must have a strong portfolio and experience with Figma.",
    jobUrl: "https://example.com/job/2",
    benefits: ["Free Meals", "Travel Credits", "Gym Membership"],
    qualifications: ["Mastery of Figma", "Strong visual design sense"]
  },
  {
    title: "Backend Developer (Go)",
    company: "Stripe",
    location: "Hyderabad, TS",
    salary: "₹40L - ₹60L",
    jobType: "Full-time",
    description: "Build robust and scalable payment processing infrastructure used by millions of businesses. Proficiency in Go and distributed systems is required.",
    jobUrl: "https://example.com/job/3",
    benefits: ["Hybrid Work", "Stock Options", "Education Allowance"],
    qualifications: ["Proficiency in Go", "Experience with microservices"]
  },
  {
    title: "Fullstack Developer",
    company: "Netflix",
    location: "Mumbai, MH",
    salary: "₹35L - ₹55L",
    jobType: "Full-time",
    description: "Work on internal tools that power the world's leading streaming service. React and Node.js expertise needed.",
    jobUrl: "https://example.com/job/4",
    benefits: ["Unlimited PTO", "Subsidized Meals", "Health Insurance"],
    qualifications: ["Fullstack proficiency", "Next.js experience"]
  },
  {
    title: "DevOps Engineer",
    company: "Google",
    location: "Pune, MH",
    salary: "₹50L - ₹75L",
    jobType: "Full-time",
    description: "Manage and scale our cloud infrastructure. Experience with Kubernetes, Docker, and Terraform is a must.",
    jobUrl: "https://example.com/job/5",
    benefits: ["Global Relocation", "Stock Grants", "Childcare"],
    qualifications: ["K8s mastery", "Terraform expert"]
  },
  {
    title: "Mobile App Developer (React Native)",
    company: "Zomato",
    location: "Gurgaon, HR",
    salary: "₹25L - ₹40L",
    jobType: "Full-time",
    description: "Build the next generation of food delivery experiences for millions of users.",
    jobUrl: "https://example.com/job/6",
    benefits: ["Performance Bonus", "Health Care"],
    qualifications: ["React Native experience", "Mobile UI skills"]
  },
  {
    title: "Data Scientist",
    company: "Microsoft",
    location: "Bangalore, KA",
    salary: "₹45L - ₹65L",
    jobType: "Full-time",
    description: "Analyze large datasets and build machine learning models to improve our products.",
    jobUrl: "https://example.com/job/7",
    benefits: ["Remote work", "Education Grant"],
    qualifications: ["Python", "Spark", "PyTorch"]
  },
  {
    title: "Security Engineer",
    company: "Amazon Web Services",
    location: "Hyderabad, TS",
    salary: "₹55L - ₹80L",
    jobType: "Full-time",
    description: "Defend against threats and ensure the security of cloud services at scale.",
    jobUrl: "https://example.com/job/8",
    benefits: ["Pension", "Private Health"],
    qualifications: ["Cloud Security certs", "Ethical Hacking"]
  },
  {
    title: "Product Manager",
    company: "Uber",
    location: "Bangalore, KA",
    salary: "₹40L - ₹60L",
    jobType: "Full-time",
    description: "Lead the development of features that improve driver efficiency and rider satisfaction.",
    jobUrl: "https://example.com/job/9",
    benefits: ["Car allowance", "Stock options"],
    qualifications: ["Product experience", "Data-driven mindset"]
  },
  {
    title: "Software Engineer (Rust)",
    company: "Coinbase",
    location: "Remote",
    salary: "₹60L - ₹90L",
    jobType: "Full-time",
    description: "Help build the most trusted cryptocurrency platform in the world using Rust.",
    jobUrl: "https://example.com/job/10",
    benefits: ["Cryto bonus", "Remote setup"],
    qualifications: ["Rust expertise", "Cryptography knowledge"]
  },
  {
    title: "Machine Learning Engineer",
    company: "OpenAI",
    location: "Remote, India",
    salary: "₹80L - ₹120L",
    jobType: "Full-time",
    description: "Work on training and fine-tuning large language models to ensure AGI benefits humanity.",
    jobUrl: "https://example.com/job/11",
    benefits: ["Equity", "Flexible hours"],
    qualifications: ["Deep Learning mastery", "Python skills"]
  },
  {
    title: "Customer Support Engineer",
    company: "Slack",
    location: "Pune, MH",
    salary: "₹15L - ₹25L",
    jobType: "Full-time",
    description: "Provide exceptional support to our users and help troubleshoot technical issues.",
    jobUrl: "https://example.com/job/12",
    benefits: ["Wellness allowance", "Internet stipend"],
    qualifications: ["Communication skills", "Basic HTML/CSS"]
  },
  {
    title: "Marketing Designer",
    company: "Spotify",
    location: "Mumbai, MH",
    salary: "₹25L - ₹35L",
    jobType: "Contract",
    description: "Create engaging visual content for our marketing campaigns across social media.",
    jobUrl: "https://example.com/job/13",
    benefits: ["Music subscription", "Coworking allowance"],
    qualifications: ["Motion design", "Graphic design"]
  },
  {
    title: "Sales Representative",
    company: "Salesforce",
    location: "New Delhi, DL",
    salary: "₹20L - ₹40L",
    jobType: "Full-time",
    description: "Help businesses transform their operations with the world's leading CRM.",
    jobUrl: "https://example.com/job/14",
    benefits: ["Commission", "Travel expense"],
    qualifications: ["Sales experience", "Communication"]
  },
  {
    title: "Quality Assurance Engineer",
    company: "Flipkart",
    location: "Bangalore, KA",
    salary: "₹18L - ₹28L",
    jobType: "Full-time",
    description: "Ensure the quality and reliability of our e-commerce platform through automation testing.",
    jobUrl: "https://example.com/job/15",
    benefits: ["Food coupons", "Medical insurance"],
    qualifications: ["Selenium", "Java", "Testing basics"]
  },
  {
    title: "Blockchain Developer",
    company: "Polygon",
    location: "Remote",
    salary: "₹50L - ₹80L",
    jobType: "Full-time",
    description: "Develop smart contracts and bridge infrastructure for Ethereum scaling.",
    jobUrl: "https://example.com/job/16",
    benefits: ["Tokens", "Annual retreat"],
    qualifications: ["Solidity", "Smart contracts"]
  },
  {
    title: "Game Developer (Unity)",
    company: "Nazara Technologies",
    location: "Mumbai, MH",
    salary: "₹20L - ₹35L",
    jobType: "Full-time",
    description: "Create immersive mobile gaming experiences for a global audience.",
    jobUrl: "https://example.com/job/17",
    benefits: ["Game credits", "Health"],
    qualifications: ["Unity", "C#", "Mobile dev"]
  },
  {
    title: "Embedded Systems Engineer",
    company: "Tesla",
    location: "Bangalore, KA",
    salary: "₹45L - ₹65L",
    jobType: "Full-time",
    description: "Write low-level firmware for electric vehicle diagnostics and control systems.",
    jobUrl: "https://example.com/job/18",
    benefits: ["Stock", "Car discount"],
    qualifications: ["C/C++", "RTOS", "FMEA"]
  },
  {
    title: "Cloud Architect",
    company: "Oracle",
    location: "Hyderabad, TS",
    salary: "₹55L - ₹85L",
    jobType: "Full-time",
    description: "Design and implement cloud-native architectures for enterprise customers.",
    jobUrl: "https://example.com/job/19",
    benefits: ["Life insurance", "Education support"],
    qualifications: ["OCI Certs", "Architecture design"]
  },
  {
    title: "Content Writer",
    company: "HubSpot",
    location: "Remote",
    salary: "₹10L - ₹18L",
    jobType: "Contract",
    description: "Produce high-quality blog posts and articles focused on inbound marketing.",
    jobUrl: "https://example.com/job/20",
    benefits: ["Weekly stipend", "Resource books"],
    qualifications: ["SEO writing", "English fluency"]
  },
  {
    title: "IT Project Manager",
    company: "Infosys",
    location: "Pune, MH",
    salary: "₹25L - ₹40L",
    jobType: "Full-time",
    description: "Lead software development projects for global clients across various industries.",
    jobUrl: "https://example.com/job/21",
    benefits: ["Standard corporate perks"],
    qualifications: ["PMP Certification", "Management skills"]
  },
  {
    title: "AI Specialist",
    company: "Meta",
    location: "Remote",
    salary: "₹70L - ₹110L",
    jobType: "Full-time",
    description: "Research and implement advancements in generative AI and neural networks.",
    jobUrl: "https://example.com/job/22",
    benefits: ["Hardware stipend", "Top equity"],
    qualifications: ["PhD in AI", "Research publications"]
  },
  {
    title: "Site Reliability Engineer",
    company: "Twitter/X",
    location: "Bengaluru",
    salary: "₹45L - ₹70L",
    jobType: "Full-time",
    description: "Maintain the uptime and scalability of a global real-time social platform.",
    jobUrl: "https://example.com/job/23",
    benefits: ["No-office remote", "Stock options"],
    qualifications: ["Linux systems", "SRE concepts"]
  },
  {
    title: "Digital Marketing Manager",
    company: "Adobe",
    location: "Noida, UP",
    salary: "₹28L - ₹45L",
    jobType: "Full-time",
    description: "Drive adoption of Adobe's creative cloud suite through strategic digital campaigns.",
    jobUrl: "https://example.com/job/24",
    benefits: ["Gym", "Software access"],
    qualifications: ["Marketing expert", "Campaign management"]
  },
  {
    title: "Staff Research Engineer",
    company: "DeepMind",
    location: "Remote",
    salary: "₹90L - ₹140L",
    jobType: "Full-time",
    description: "Solve intelligence and push the boundaries of AI capabilities.",
    jobUrl: "https://example.com/job/25",
    benefits: ["Premier healthcare", "Unlimited learning"],
    qualifications: ["Strong research background", "Mathematical excellence"]
  },
  {
    title: "Frontend Developer (Vue.js)",
    company: "GitLab",
    location: "Remote",
    salary: "₹35L - ₹55L",
    jobType: "Full-time",
    description: "Help build the most comprehensive DevSecOps platform with Vue.js.",
    jobUrl: "https://example.com/job/26",
    benefits: ["Remote-first", "Co-working space"],
    qualifications: ["Vue.js mastery", "Open-source contributor"]
  },
  {
    title: "Network Engineer",
    company: "Cisco Systems",
    location: "Bangalore, KA",
    salary: "₹22L - ₹38L",
    jobType: "Full-time",
    description: "Maintain and upgrade enterprise-grade network infrastructure for our clients.",
    jobUrl: "https://example.com/job/27",
    benefits: ["Internet reimbursement", "Travel"],
    qualifications: ["CCNA/CCNP", "Network security"]
  },
  {
    title: "Lead Data Analyst",
    company: "Paytm",
    location: "Noida, UP",
    salary: "₹24L - ₹42L",
    jobType: "Full-time",
    description: "Lead a team of analysts to drive insights and improve conversion for financial products.",
    jobUrl: "https://example.com/job/28",
    benefits: ["Wellness credits", "Lunch provided"],
    qualifications: ["SQL expert", "Tableau/PowerBI"]
  },
  {
    title: "Technical Artist",
    company: "Electronic Arts (EA)",
    location: "Hyderabad, TS",
    salary: "₹30L - ₹50L",
    jobType: "Full-time",
    description: "Bridge the gap between art and code for our flagship AAA titles.",
    jobUrl: "https://example.com/job/29",
    benefits: ["Free games", "Relocation support"],
    qualifications: ["Shader programming", "3D assets"]
  },
  {
    title: "HR Director",
    company: "TCS",
    location: "Chennai, TN",
    salary: "₹40L - ₹65L",
    jobType: "Full-time",
    description: "Oversee global talent management and organizational development.",
    jobUrl: "https://example.com/job/30",
    benefits: ["Standard global perks"],
    qualifications: ["HR leadership", "Talent management"]
  }
];
